/**
 * The replay tape, flattened for Foundry.
 *
 * `scripts/arb/series/base-ethusd.json` is the real thing: Chainlink ETH/USD rounds published on Base,
 * captured at a pinned block by `scripts/arb/capture.ts`. It stores `[updatedAt, answer]` pairs, and
 * `vm.parseJson` cannot hand a Solidity test an array of mixed-type pairs -- it encodes each pair as a
 * length-prefixed heterogeneous tuple that `abi.decode` refuses. So this script rewrites the same rounds
 * as two parallel integer arrays that `vm.parseJsonUintArray` reads directly.
 *
 * NOTHING IS RESAMPLED AND NOTHING IS INVENTED. Every entry is a round the feed actually published, at
 * the second it published it, in the order it published them; the replay steps on those timestamps rather
 * than on a grid of our choosing, so the cadence of the simulation is the cadence of the real feed. The
 * output carries `keccak256` of the source file's bytes, and `MarkoutReplay.t.sol` re-reads the source and
 * asserts that hash before it uses a single price -- so a regenerated tape that no longer matches its
 * source fails the test rather than quietly changing the result.
 *
 *   tsx scripts/markout/tape.ts            regenerate contracts/test/markout/tape.json
 *   tsx scripts/markout/tape.ts --check    fail if the committed file is not what this script produces
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { keccak256, toHex } from 'viem';
import { loadSeries, SERIES_PATH, type PriceSeries } from '../arb/tape.ts';

const HERE = dirname(fileURLToPath(import.meta.url)); // scripts/markout
const ROOT = resolve(HERE, '..', '..');
export const TAPE_PATH = resolve(ROOT, 'contracts/test/markout/tape.json');

/** The demo book's expiry. A replay window is seven days long and can start anywhere on the tape. */
const HORIZON_SECONDS = 7 * 24 * 3_600;

export interface MarkoutTape {
  kind: 'strikeline-markout-tape';
  note: string;
  source: string;
  /** `keccak256` of the source file's bytes. Asserted in Solidity before the tape is used. */
  sourceKeccak256: `0x${string}`;
  sourceRounds: number;
  chainId: number;
  feed: string;
  feedDescription: string;
  readAtBlock: number;
  decimals: number;
  /** Longest replay window the tape can carry, in seconds. */
  horizonSeconds: number;
  /** How many seven-day windows the tape can start, at `windowOffsetSeconds` apart. */
  windows: number;
  windowOffsetSeconds: number;
  firstTimestamp: number;
  lastTimestamp: number;
  /** Publication time of every round, ascending. */
  t: number[];
  /** The answer of that round, in feed decimals. Always below 2^53, so it survives JSON. */
  answer: number[];
}

/** Half a day, so a 10.7-day capture yields eight overlapping seven-day windows. */
const WINDOW_OFFSET_SECONDS = 12 * 3_600;

export function buildTape(): MarkoutTape {
  const series = loadSeries();
  const sourceBytes = readFileSync(SERIES_PATH);
  const span = series.lastTimestamp - series.firstTimestamp;
  if (span < HORIZON_SECONDS) {
    throw new Error(
      `the captured window is ${span / 86_400} days, shorter than the ` +
        `${HORIZON_SECONDS / 86_400}-day horizon this replay needs`,
    );
  }

  const t: number[] = [];
  const answer: number[] = [];
  let previous = 0;
  for (const [roundTs, rawAnswer] of series.ticks) {
    if (roundTs <= previous) throw new Error(`rounds are not strictly ascending at ${roundTs}`);
    previous = roundTs;
    const raw = Number(rawAnswer);
    if (!Number.isSafeInteger(raw)) {
      throw new Error(`answer ${rawAnswer} does not survive a JSON number`);
    }
    t.push(roundTs);
    answer.push(raw);
  }

  return {
    kind: 'strikeline-markout-tape',
    note:
      'SIMULATION INPUT. Every Chainlink ETH/USD round published on Base in the captured window, ' +
      'at the second it was published. Generated by scripts/markout/tape.ts; do not edit by hand.',
    source: 'scripts/arb/series/base-ethusd.json',
    sourceKeccak256: keccak256(toHex(sourceBytes)),
    sourceRounds: series.ticks.length,
    chainId: series.chainId,
    feed: series.feed,
    feedDescription: series.feedDescription,
    readAtBlock: series.readAtBlock,
    decimals: series.decimals,
    horizonSeconds: HORIZON_SECONDS,
    windows: Math.floor((span - HORIZON_SECONDS) / WINDOW_OFFSET_SECONDS) + 1,
    windowOffsetSeconds: WINDOW_OFFSET_SECONDS,
    firstTimestamp: series.firstTimestamp,
    lastTimestamp: series.lastTimestamp,
    t,
    answer,
  };
}

function main(): void {
  const check = process.argv.includes('--check');
  const tape = buildTape();
  const text = `${JSON.stringify(tape, null, 2)}\n`;

  if (check) {
    if (!existsSync(TAPE_PATH)) {
      console.error(`missing ${TAPE_PATH} -- run \`tsx scripts/markout/tape.ts\``);
      process.exit(1);
    }
    const onDisk = readFileSync(TAPE_PATH, 'utf8');
    if (onDisk !== text) {
      console.error('contracts/test/markout/tape.json is not what scripts/markout/tape.ts produces.');
      process.exit(1);
    }
    console.log(`tape.json matches its source (${tape.t.length} rounds)`);
    return;
  }

  writeFileSync(TAPE_PATH, text);
  const px = (a: number) => (a / 10 ** tape.decimals).toFixed(2);
  console.log(`wrote ${TAPE_PATH}`);
  console.log(
    `  ${tape.t.length} real ${tape.feedDescription} rounds on chain ${tape.chainId} over ` +
      `${((tape.lastTimestamp - tape.firstTimestamp) / 86_400).toFixed(2)} days, ` +
      `${tape.windows} seven-day windows`,
  );
  console.log(`  first ${px(tape.answer[0])}  last ${px(tape.answer[tape.answer.length - 1])}`);
  console.log(`  source keccak256 ${tape.sourceKeccak256}`);
}

main();
