/**
 * The design tokens, readable from TypeScript.
 *
 * CSS owns the values (`src/app/globals.css`); this module is the typed handle on them for the
 * places a class name cannot reach: SVG `fill`/`stroke` props, chart scales, `<meta name="theme-color">`,
 * the Mantine theme, and motion configs. Every entry here has a counterpart custom property, and the
 * two are kept in step by `node scripts/contrast.mjs`, which reads the same numbers.
 *
 * Rule of thumb: reach for a Mantine prop or a Tailwind class first. Use `color()` only where
 * neither can be applied.
 *
 * The palette is DARK, and there is no light branch. See the design spec and the header of
 * `src/app/globals.css` for why each value is where it is.
 */

// ---------------------------------------------------------------------------
// Colors
// ---------------------------------------------------------------------------

export const COLOR_TOKENS = [
  'bg',
  'surface',
  'surface-2',
  'surface-3',
  'line',
  'line-strong',
  'ink',
  'ink-2',
  'ink-3',
  'ink-inverse',
  'accent',
  'accent-hover',
  'accent-ink',
  'accent-soft',
  'accent-dim',
  'pos',
  'pos-soft',
  'neg',
  'neg-soft',
  'warn',
  'warn-soft',
  'scrim',
] as const;

export type ColorToken = (typeof COLOR_TOKENS)[number];

/** Authored OKLCH, for documentation and for the contrast audit. */
export const COLOR_OKLCH: Record<ColorToken, string> = {
  bg: 'oklch(0.155 0.006 240)',
  surface: 'oklch(0.192 0.007 240)',
  'surface-2': 'oklch(0.228 0.008 240)',
  'surface-3': 'oklch(0.268 0.009 240)',
  line: 'oklch(0.30 0.010 240)',
  'line-strong': 'oklch(0.40 0.012 240)',
  ink: 'oklch(0.965 0.004 240)',
  'ink-2': 'oklch(0.755 0.008 240)',
  'ink-3': 'oklch(0.66 0.010 240)',
  'ink-inverse': 'oklch(0.16 0.008 240)',
  accent: 'oklch(0.80 0.115 195)',
  'accent-hover': 'oklch(0.86 0.115 195)',
  'accent-ink': 'oklch(0.16 0.02 195)',
  'accent-soft': 'oklch(0.28 0.045 195)',
  'accent-dim': 'oklch(0.42 0.06 195)',
  pos: 'oklch(0.78 0.145 152)',
  'pos-soft': 'oklch(0.27 0.05 152)',
  neg: 'oklch(0.685 0.175 22)',
  'neg-soft': 'oklch(0.27 0.06 22)',
  warn: 'oklch(0.80 0.115 78)',
  'warn-soft': 'oklch(0.28 0.05 78)',
  scrim: 'oklch(0.09 0.006 240 / 0.72)',
};

/**
 * The same colors resolved to sRGB. Only for contexts that cannot evaluate `oklch()` or `var()`:
 * `theme-color` meta, the Mantine theme's color tuples, OG image generation, `<canvas>`.
 * In the DOM, use `color()`.
 *
 * Gamut-clipped the way a display clips, which is also what `scripts/contrast.mjs` measures, so the
 * ratio in the audit is the ratio a browser paints.
 */
export const COLOR_SRGB: Record<ColorToken, `#${string}`> = {
  bg: '#0a0d0f',
  surface: '#111517',
  'surface-2': '#191d20',
  'surface-3': '#22272a',
  line: '#292f32',
  'line-strong': '#42494e',
  ink: '#f1f4f6',
  'ink-2': '#abb0b4',
  'ink-3': '#8d9398',
  'ink-inverse': '#0a0e10',
  accent: '#4ed5d5',
  'accent-hover': '#65e9e8',
  'accent-ink': '#031010',
  'accent-soft': '#043030',
  'accent-dim': '#1c5757',
  pos: '#66d288',
  'pos-soft': '#112d1a',
  neg: '#f36567',
  'neg-soft': '#3f1919',
  warn: '#e6b463',
  'warn-soft': '#362508',
  scrim: '#020303',
};

/** `color('accent')` -> `'var(--accent)'`. */
export function color(token: ColorToken): string {
  return `var(--${token})`;
}

/**
 * A tint of a token, for chart bands and hover washes. Keeps alpha out of component code so the
 * palette stays auditable.
 *
 * @param percent 0-100, how much of the token survives the mix with transparent.
 */
export function colorMix(token: ColorToken, percent: number): string {
  const clamped = Math.min(100, Math.max(0, percent));
  return `color-mix(in oklch, var(--${token}) ${clamped}%, transparent)`;
}

// ---------------------------------------------------------------------------
// Ramps
// ---------------------------------------------------------------------------

/**
 * Ten-step ramps, because that is the shape Mantine's `theme.colors` takes.
 *
 * These are not a second palette: shades 8 and 9 of `petrol` are `--accent` and `--accent-hover`,
 * shade 1 is `--accent-soft`, shade 4 is `--accent-dim`; `slate` 1/2/3/4/6/7/9 are `--bg`,
 * `--surface-3`, `--line`, `--line-strong`, `--ink-3`, `--ink-2` and `--ink`. The intermediate
 * steps exist only so Mantine's `light`/`outline`/`filled` variants have somewhere to go.
 *
 * Generated by walking a fixed hue at descending OKLCH lightness with the chroma capped to the
 * sRGB gamut at each step; the OKLCH that produced each hex is in the comment beside it.
 */
export type ColorRamp = readonly [
  string, string, string, string, string, string, string, string, string, string,
];

export const RAMPS = {
  /**
   * The accent. Hue 195 — deliberately not the 245-250 every library ships as its default.
   *
   * The ramp still runs light to dark, because that is the order Mantine's variant maths assumes.
   * On a dark scheme it reads the *light* end for text and the dark end for fills, which is why the
   * bright accent sits at 4 rather than at 8: `--mantine-color-petrol-light-color` resolves to
   * shade 3, and `-light` tints with shade 8 at low alpha over the near-black body.
   */
  petrol: [
    '#daf7f6', // 0  oklch(0.955 0.030 195)
    '#b3eeee', // 1  oklch(0.910 0.060 195)
    '#65e9e8', // 2  oklch(0.860 0.115 195)   = --accent-hover
    '#5adfde', // 3  oklch(0.830 0.115 195)
    '#4ed5d5', // 4  oklch(0.800 0.115 195)   = --accent
    '#47b6b6', // 5  oklch(0.715 0.100 195)
    '#379797', // 6  oklch(0.620 0.088 195)
    '#207070', // 7  oklch(0.500 0.075 195)
    '#1c5757', // 8  oklch(0.420 0.060 195)   = --accent-dim
    '#043030', // 9  oklch(0.280 0.045 195)   = --accent-soft
  ],
  /** The neutrals. Overrides Mantine's `gray`, which is otherwise a warm-blue default. */
  slate: [
    '#f1f4f6', // 0  oklch(0.965 0.004 240)   = --ink
    '#dbdfe2', // 1  oklch(0.900 0.006 240)
    '#c0c5c8', // 2  oklch(0.820 0.007 240)
    '#abb0b4', // 3  oklch(0.755 0.008 240)   = --ink-2
    '#93999d', // 4  oklch(0.680 0.009 240)
    '#8d9398', // 5  oklch(0.660 0.010 240)   = --ink-3
    '#5e6469', // 6  oklch(0.500 0.011 240)
    '#42494e', // 7  oklch(0.400 0.012 240)   = --line-strong
    '#292f32', // 8  oklch(0.300 0.010 240)   = --line
    '#111517', // 9  oklch(0.192 0.007 240)   = --surface
  ],
  /** Positive. Gains, fills received, a coverage check that passed. */
  moss: [
    '#dcf7e2', // 0  oklch(0.950 0.040 152)
    '#baedc6', // 1  oklch(0.900 0.075 152)
    '#99e6ad', // 2  oklch(0.860 0.110 152)
    '#7fdc9a', // 3  oklch(0.820 0.130 152)
    '#66d288', // 4  oklch(0.780 0.145 152)   = --pos
    '#4fb772', // 5  oklch(0.700 0.140 152)
    '#359658', // 6  oklch(0.600 0.130 152)
    '#186f3b', // 7  oklch(0.480 0.115 152)
    '#0e4926', // 8  oklch(0.360 0.085 152)
    '#112d1a', // 9  oklch(0.270 0.050 152)   = --pos-soft
  ],
  /** Negative. Losses, a revert, a quote the wallet cannot deliver. */
  ember: [
    '#ffddda', // 0  oklch(0.930 0.045 22)
    '#ffc3c0', // 1  oklch(0.880 0.080 22)
    '#ffa9a6', // 2  oklch(0.830 0.115 22)
    '#ff8785', // 3  oklch(0.760 0.150 22)
    '#f36567', // 4  oklch(0.685 0.175 22)    = --neg
    '#de4d52', // 5  oklch(0.620 0.180 22)
    '#c5353e', // 6  oklch(0.550 0.180 22)
    '#99212b', // 7  oklch(0.450 0.155 22)
    '#681a1f', // 8  oklch(0.350 0.110 22)
    '#3f1919', // 9  oklch(0.270 0.060 22)    = --neg-soft
  ],
  /** Warning. A stale read, a thin wallet, a simulation label. */
  amber: [
    '#fdeed7', // 0  oklch(0.955 0.035 78)
    '#f8ddb5', // 1  oklch(0.910 0.060 78)
    '#f5cd90', // 2  oklch(0.870 0.090 78)
    '#efc178', // 3  oklch(0.835 0.105 78)
    '#e6b463', // 4  oklch(0.800 0.115 78)    = --warn
    '#ca9c4e', // 5  oklch(0.720 0.110 78)
    '#a77e39', // 6  oklch(0.620 0.100 78)
    '#7e5d24', // 7  oklch(0.500 0.085 78)
    '#553e15', // 8  oklch(0.380 0.065 78)
    '#362508', // 9  oklch(0.280 0.050 78)    = --warn-soft
  ],
} as const satisfies Record<string, ColorRamp>;

export type RampName = keyof typeof RAMPS;

/**
 * The shade Mantine fills a non-primary surface with. 8, not the library default 6: on a dark
 * scheme a `filled` variant paints shade 8 and writes white on it, and only the dark end of these
 * ramps carries white at 4.5:1. The primary colour never reaches this — `cssVariablesResolver`
 * overrides `--mantine-primary-color-filled` with `--accent` directly.
 */
export const PRIMARY_SHADE = 8;

// ---------------------------------------------------------------------------
// Type
// ---------------------------------------------------------------------------

export const TEXT_TOKENS = [
  'micro',
  'mini',
  'meta',
  'body',
  'lead',
  'title',
  'section',
  'display',
] as const;

export type TextToken = (typeof TEXT_TOKENS)[number];

/** Font sizes in px, for SVG `font-size` on chart labels and for the Mantine type scale. */
export const TEXT_PX: Record<TextToken, number> = {
  micro: 11,
  mini: 12,
  meta: 13,
  body: 14,
  lead: 16,
  title: 20,
  section: 26,
  display: 34,
};

/** The two line-height rhythms: dense numeric rows, and prose. */
export const LEADING = { num: 1.2, prose: 1.45 } as const;

/** Family stacks, for SVG text and canvas where `font-sans` cannot apply. */
export const FONT_STACK = {
  sans: 'var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif',
  mono: 'var(--font-geist-mono), ui-monospace, "SFMono-Regular", monospace',
} as const;

// ---------------------------------------------------------------------------
// Layout
// ---------------------------------------------------------------------------

/** 8px base grid; 4px is allowed only inside dense controls. */
export const GRID_PX = 8;
export const CONTENT_MAX_PX = 1280;
/** The ticket beside the chart. the layout spec fixes it at 380. */
export const CARD_MAX_PX = 380;
export const GUTTER_PX = 24;
/** Table row height, fixed so streaming values never shift the layout. */
export const ROW_HEIGHT_PX = 44;

export const RADIUS_PX = { card: 16, field: 12, control: 8, pill: 999 } as const;

// ---------------------------------------------------------------------------
// Stacking
// ---------------------------------------------------------------------------

/**
 * The whole stacking order of the app. Portals and libraries that take a numeric z-index read it
 * from here; markup uses the matching `z-modal` / `z-toast` utilities.
 */
export const Z = {
  dropdown: 10,
  sticky: 20,
  appBar: 25,
  modalBackdrop: 30,
  modal: 40,
  toast: 50,
  tooltip: 60,
} as const;

export type ZLayer = keyof typeof Z;

// ---------------------------------------------------------------------------
// Motion
// ---------------------------------------------------------------------------

export const EASE_OUT_QUART = 'cubic-bezier(0.165, 0.84, 0.44, 1)';

/** The same curve as control points, for animation libraries that take an array. */
export const EASE_OUT_QUART_POINTS = [0.165, 0.84, 0.44, 1] as const;

/** Milliseconds. State changes only; nothing in the app animates longer than `slow`. */
export const DURATION_MS = { fast: 140, base: 170, slow: 200 } as const;

export type DurationStep = keyof typeof DURATION_MS;

/**
 * True when the visitor asked for reduced motion. Returns `false` during SSR and on the first
 * client render, so read it in an effect (or via a hook) rather than during render if the result
 * changes markup.
 */
export function prefersReducedMotion(): boolean {
  if (typeof window === 'undefined' || typeof window.matchMedia !== 'function') return false;
  return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

/**
 * Duration in ms for a JS-driven animation, already collapsed to 0 under reduced motion. CSS
 * transitions do not need this — `globals.css` neutralises them centrally.
 */
export function duration(step: DurationStep): number {
  return prefersReducedMotion() ? 0 : DURATION_MS[step];
}
